spring:
  application:
    name: blog-demo
#  datasource:
#    url: jdbc:mysql://localhost:3306/test
#    username: root
#    password: root
#    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8080
